# <b>Àlgebra Linear: fundamentos e aplicações em Ciência de Dados</b>

Autor: Ronisson Lucas Calmon da Conceição

GitHub: https://github.com/ronissonlucas <br>
Linkdin: https://www.linkedin.com/in/ronisson-lucas-calmon-da-concei%C3%A7%C3%A3o-7aa884202/ <br>
Facebook: https://www.facebook.com/ronisson.lucas

Tópicos:
1. Vetor
2. Matrizes
3. Sistemas Lineares
4. Determinante
5. Produto interno
6. Norma
7. Combinação Linear
8. Hands On! - Parte I
9. Hands On! - Parte II
10. Próximos passos: Rede Neural
11. Adendos

# 1. Vetor

In [1]:
import numpy as np

* Vetor: módulo, direção e sentido (array unidimensional 1-D).

$\mathbf{x} = \left[
\begin{array}{c c c}
1\\
7\\
-1\\
\end{array}\right]
$$ $

In [2]:
x = np.array([[1], [7], [-1]])
x

array([[ 1],
       [ 7],
       [-1]])

In [3]:
x = np.array([1, 7, -1])
x.shape = (x.shape[0],1)
x

array([[ 1],
       [ 7],
       [-1]])

Igualdade

$\mathbf{u} = \left(x_1, y_1, z_1 \right)$, $\mathbf{v} = \left(x_2, y_2, z_2\right)$

$\mathbf{u} = \mathbf{v} \Leftrightarrow x_1 = x_2, y_1 = y_2, z_1 = z_2$

In [4]:
u = np.array([1, 4, 100])
v = np.array([1, np.log2(16), np.power(10, 2)])

In [5]:
u == v

array([ True,  True,  True])

Soma e multiplicação por escalar

$\mathbf{u}+\mathbf{v} = (x_1+x_2, y_1+y_2, z_1+z_2)$ <br>
$a\mathbf{v} = (ax_1,ay_1,az_1), a \in \mathbb{R}$

In [6]:
u = np.array([11, 12, 13])
v = np.array([9, 3, 2])
u+v

array([20, 15, 15])

In [7]:
10*u

array([110, 120, 130])

Produto escalar (ou produto interno)

$\mathbf{u} \cdot \mathbf{v} = x_1x_2+y_1y_2+z_1z_2$

In [8]:
sum(u*v)

161

In [9]:
np.inner(u,v)

161

Dois vetores são ortogonais ou perpendiculares se o produto interno entre eles for nulo.

$\mathbf{u} \cdot \mathbf{v} = 0 \Rightarrow u \perp v$

Módulo ou norma de um vetor

$|\mathbf{v}| = \sqrt{\mathbf{v} \cdot \mathbf{v}}= \sqrt{x_1x_1+y_1y_1} = \sqrt{x_1^2+y_1^2}$ <br>
$|\mathbf{v}| = \sqrt{x_1^2+y_1^2+z_1^2}$

In [10]:
u = np.array([3,-4])

In [11]:
np.sqrt(np.inner(u, u))

5.0

Generalizando para o $\mathbb{R}^n$ podemos definir todas as operações anteriores.

$\mathbf{x} = \left[
\begin{array}{c c c}
x_1\\
x_2\\
\vdots\\
x_n\\
\end{array}\right]
$$ $

$\mathbf{x} \in \mathbb{R}^n$

# 2. Matriz

* representação tabular de dados;
* notação: $A_{m \times n}$.

$$A= \left[
\begin{array}{c c c}
a_{11}&\ldots& a_{1n}\\
a_{21}& \ldots& a_{2n}\\
\vdots&\ddots &\vdots\\ a_{m1}&\ldots& a_{mn}
\end{array}\right]
$$ 

In [12]:
import numpy as np

$$A_{2 \times 2}= \left[
\begin{array}{c c c}
-11& 2\\
7& 15\\
\end{array}\right]
$$ 

In [13]:
matrix = np.array([[-11, 2], [7, 15]])

In [14]:
matrix

array([[-11,   2],
       [  7,  15]])

In [15]:
type(matrix)

numpy.ndarray

In [16]:
matrix.shape

(2, 2)

In [17]:
matrix.ndim  #número de dimensões

2

### 2.1 Matrizes importantes

1. Matriz Quadrada: matriz em que o número de linhas é igual ao número de colunas ($m=n$).

$$A_{2 \times 2}= \left[
\begin{array}{c c c}
-1& 2\\
4& 5\\
\end{array}\right]
$$ 

In [18]:
A = np.array([[-1, 2], [4, 5]])

In [19]:
A

array([[-1,  2],
       [ 4,  5]])

2. Matriz Nula: matriz em que todos os elementos são nulos, ou seja, $a_{ij}=0$ para todo $i$ e $j$.

$$B_{2 \times 3}= \left[
\begin{array}{c c c}
0& 0 & 0\\
0& 0 & 0\\
\end{array}\right]
$$ 

In [20]:
B = np.array([[0, 0, 0], [0, 0, 0]])
B

array([[0, 0, 0],
       [0, 0, 0]])

In [21]:
B = np.zeros(shape = (2, 3))
B

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
K = np.zeros(shape = (10, 10))
K

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

3. Matriz-Coluna: matriz que possui uma única coluna ($A_{m \times 1}$).

$$C_{4 \times 1}= \left[
\begin{array}{c c c}
-1\\
2\\
10\\
5\\
\end{array}\right]
$$ 

In [23]:
C = np.array([[-1], [2], [10], [5]])
C

array([[-1],
       [ 2],
       [10],
       [ 5]])

4. Matriz-Linha: matriz com uma única linha ($A_{1 \times n}$)

$$D_{4 \times 1}= \left[
\begin{array}{c c c}
-1 & 2 & 10 & 5\\
\end{array}\right]
$$ 

In [24]:
D = np.array([-1, 2, 10, 5])
D

array([-1,  2, 10,  5])

5. Matriz diagonal: matriz quadrada em que qualquer elemento fora da diagonal principal é nulo, isto é, $a_{ij}=0$ para $ i \neq j$.<br>

$$E_{3 \times 3}= \left[
\begin{array}{c c c}
5 & 0 & 0\\
0 & 10 & 0\\
0 & 0 & 15\\
\end{array}\right]
$$ 

In [25]:
E = np.diag(np.arange(5,16,5))
E

array([[ 5,  0,  0],
       [ 0, 10,  0],
       [ 0,  0, 15]])

5. Matriz identidade: matriz em que $a_{ij}=1$ ,  $\forall i=j$ e $a_{ij}=0$, $\forall i \neq j$. Assim, a matriz identidade, ou matriz unitária, de ordem $n$, denotada por $I{_n}$ ou, simplesmente, por $I$, é a matriz quadrada
com 1 na diagonal principal e 0 em todas as demais entradas. A matriz identidade $I$ é análoga ao escalar $1$, pois,
dada qualquer matriz $A_{m \times n}$, temos que $\mathbf{AI =IA = A}$. Para uma matriz $B_{n \times 1}$, verifica-se $\mathbf{IB=B}$

$$I_{3}= \left[
\begin{array}{c c c}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1\\
\end{array}\right]
$$ 

In [26]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

8. Matriz simétrica: matriz quadrada em que $a_{ij} = a_{ji}$ para quaisquer $i,j$ e $A^{T} = A$.

$$F_{3 \times 3} = \left[
\begin{array}{c c c}
4 & 3 & -1\\
3 & 2 & 0\\
-1 & 0 & 5\\
\end{array}\right]
$$ 

In [28]:
F = np.array([[4, 3, -1], [3, 2, 0], [-1, 0, 5]])
F

array([[ 4,  3, -1],
       [ 3,  2,  0],
       [-1,  0,  5]])

In [29]:
F.T == F

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

9. Matriz Idempotente: matriz quadrada em que $A \cdot A = A$ .

$$L_{2 \times 2}= \left[
\begin{array}{c c c}
5& -5\\
4& -4\\
\end{array}\right]
$$ 

In [30]:
L = np.array([[5, -5], [4, -4]])
L

array([[ 5, -5],
       [ 4, -4]])

In [31]:
np.dot(L, L)

array([[ 5, -5],
       [ 4, -4]])

### 2.2 Operações matriciais

2.2.1 Adição e multiplicação por escalar

* As matrizes precisam ter a mesma ordem.

$$A_{2 \times 2}= \left[
\begin{array}{c c c}
1& 3\\
2& 7\\
\end{array}\right]
$$ 
$$B_{2 \times 2}= \left[
\begin{array}{c c c}
2& 5\\
5& 3\\
\end{array}\right]
$$ 

$$A+B = \left[
\begin{array}{c c c}
1+2& 3+5\\
2+5& 7+3\\
\end{array}\right]
$$ 
$$
A+B =
\left[
\begin{array}{c c c}
3& 8\\
7& 10\\
\end{array}\right]
$$

In [32]:
A = np.array([[1, 3], [2, 7]])
B = np.array([[2, 5], [5, 3]])
soma = A+B
soma

array([[ 3,  8],
       [ 7, 10]])

Generalizando:

 $$A+B =\left[
\begin{array}{c c c}
a_{11}+ b_{11}&\ldots& a_{1n}+b_{1n}\\
a_{21}+b_{21}& \ldots& a_{2n}+b_{2n}\\
\vdots&\ddots &\vdots\\ a_{m1}+b_{m1}&\ldots& a_{mn}+ b_{mn}
\end{array}\right]
$$

Produto por escalar

$$10A_{2 \times 2}= \left[
\begin{array}{c c c}
10 \times 1& 10 \times 3\\
10 \times 2& 10 \times7\\
\end{array}\right]
$$

In [33]:
10*A

array([[10, 30],
       [20, 70]])

Generalizando:

$$kA=\left[ 
\begin{array}{c c c}
ka_{11}&\ldots& ka_{1n}\\
ka_{21}& \ldots& ka_{2n}\\
\vdots&\ddots &\vdots\\ ka_{m1}&\ldots& ka_{mn}
\end{array}\right]
$$

2.2.2 Multiplicação de matrizes

* Multiplicação entre uma matriz linha e uma matriz coluna

$\begin{bmatrix}
1 & 5 & 10 \\
\end{bmatrix} $$\begin{bmatrix}
2 \\ 
3 \\   
2\\
\end{bmatrix}$ $= $$1 \times 2 + 5 \times 3 + 10 \times 2 = 37 $.

In [34]:
u = np.array([1, 5, 10])
v = np.array([[2], [3], [2]])

In [35]:
u

array([ 1,  5, 10])

In [36]:
v

array([[2],
       [3],
       [2]])

In [37]:
np.dot(u,v)

array([37])

Generalizando:

 AB= $\begin{bmatrix}
a_{1}, & a_{2}, & ...,&a_{n}\\
\end{bmatrix} $$\begin{bmatrix}
b_{1} \\ 
b_{2} \\ 
... \\  
b_{n}\\
\end{bmatrix}$ $= $$a_{1}b_{1}$+$ $$a_{2}b_{2}$$+$ ... $+$$a_{n}b_{n}$.

* Caso geral de multiplicação de matrizes

$A_{m \times p} \cdot B_{p \times n} = C_{m \times n}$

O elemento $c_{ij}$ será obtido por meio da multiplicação dos elementos da i-ésima linha da primeira matriz pelos correspondentes elementos da j-ésima coluna da segunda matriz, com a posterior soma destes produtos.

$\left[
\begin{array}{c c c}
2 & 1\\
4 & 2\\
5 & 3\\
\end{array}\right]_{3 \times 2}
$ $\cdot \left[
\begin{array}{c c c}
1 & -1\\
0 & 4\\
\end{array}\right]_{2 \times 2}$ 
$ = \left[
\begin{array}{c c c}
2 \times 1+1\times 0 & 2 \times (-1)+1 \times 4 \\
4 \times 1+ 2 \times 0 & 4 \times(-1)+2 \times 4\\
5 \times 1+3 \times 0 & 5 \times (-1) +3 \times 4
\end{array}\right]_{3 \times 2} 
$ 
$ = \left[
\begin{array}{c c c}
2 & 2 \\
4 & 4 \\
5 & 7 \\
\end{array}\right]_{3 \times 2} 
$ 

In [38]:
A = np.array([[2, 1], [4, 2], [5, 3]])
B = np.array([[1, -1], [0, 4]])
C = np.dot(A,B)
C

array([[2, 2],
       [4, 4],
       [5, 7]])

### 2.3 Matriz transposta

A transposta de uma matriz A, denotada por $A^{T}$ ou $A' $, é a matriz obtida escrevendo as colunas de A, na mesma ordem, como linhas.

$$A= \left[
\begin{array}{c c c}
1& 7\\
8& 3\\
1 & 2\\
\end{array}\right]
$$ 

$$A^{T}= \left[
\begin{array}{c c c}
1& 8 & 1\\
7& 3 & 2\\
\end{array}\right]
$$ 

In [39]:
A = np.array([[1, 7], [8, 3], [1, 2]])
A

array([[1, 7],
       [8, 3],
       [1, 2]])

In [40]:
A.T

array([[1, 8, 1],
       [7, 3, 2]])

In [41]:
A.transpose()

array([[1, 8, 1],
       [7, 3, 2]])

### 2.4 Traço de uma matriz

O traço de uma matriz quadrada A, denotado por tr(A), é a soma dos elementos da diagonal principal, a saber, $ tr\mathbf{(A)}= a_{11}+a_{22}+a_{33}+...+a_{nn}$

$$A= \left[
\begin{array}{c c c}
2& 7 & 1\\
8& 3 & 2\\
1 & 2 & 10\\
\end{array}\right]
$$ 

In [42]:
A = np.array([[2, 7, 1], [8, 3, 2], [1, 2, 10]])
A.trace()

15

### 2.5 Matriz Inversa

Uma matriz quadrada $A$ é dita invertível, ou não singular, se existir uma matriz $B$ tal que
$AB = BA = I$ onde $I$ é a matriz identidade. Uma tal matriz $B$ é única. 

In [43]:
Z = np.array([[3,4],[1,0]])
Z_inv = np.linalg.inv(Z)

In [44]:
Z_inv

array([[ 0.  ,  1.  ],
       [ 0.25, -0.75]])

In [45]:
Z.dot(Z_inv)

array([[1., 0.],
       [0., 1.]])

# 3. Sistemas Lineares

* Um sistema linear pode ter uma única solução, múltiplas soluções ou nenhuma solução.

$\begin{cases}
a_{11}x_{1}+a_{12}x_{2}+...+a_{1n}x_{n}=b_{1} \\
a_{21}x_{1}+a_{22}x_{2}+...+a_{2n}x_{n}=b_{2} \\
..............................\\
a_{m1}x_{1}+a_{m2}x_{2}+...+a_{mn}x_{n}=b_{m}\\
\end{cases}$ em que $a_{11}, a_{12},..., a_{1n}, b_{1}, b_{2}, ..., b_{m}$

Desse sistema, destacamos as seguintes matrizes:
- matriz completa do sistema 
$\begin{bmatrix}
a_{11} & a_{12} & ... & a_{1n} &b_{1}\\
a_{21} & a_{22} & ... & a_{2n} & b_{2}\\
... & ... & ... & ...&....\\
a_{n1} & a_{n2} & ... & a_{nn}&b_{1m}\\
\end{bmatrix}$


- matriz incompleta do sistema 
$\begin{bmatrix}
a_{11} & a_{12} & ... & a_{1n}\\
a_{21} & a_{22} & ... & a_{2n}\\
... & ... & ... & ...\\
a_{n1} & a_{n2} & ... & a_{nn}\\
\end{bmatrix}$

Consideremos ainda as seguintes matrizes-colunas assosciadas ao sistema:
X = $\begin{bmatrix}
x_{1} \\
x_{2} \\
\vdots\\
x_{n}\\
\end{bmatrix}$    $\space$, B = $\begin{bmatrix}
b_{1} \\
b_{2} \\
\vdots\\
b_{m}\\
\end{bmatrix}$

$$\begin{bmatrix}
a_{11} & a_{12} & ... & a_{1n}\\
a_{21} & a_{22} & ... & a_{2n}\\
... & ... & ... & ...\\
a_{n1} & a_{n2} & ... & a_{nn}\\
\end{bmatrix}\cdot \begin{bmatrix}
x_{1} \\
x_{2} \\
\vdots\\
x_{n}\\
\end{bmatrix}=\begin{bmatrix}
b_{1} \\
b_{2} \\
\vdots\\
b_{m}\\
\end{bmatrix}$$

Representemos o sistema $\begin{cases}
3a-7b=1\\
5a+2b=4 \\
\end{cases}$ na forma matricial e encontremos sua solução.

In [46]:
A = np.array ([[3, -7], [5, 2]])
B = np.array([[1], [4]])

In [47]:
X = (np.linalg.solve(A, B))

In [48]:
X  #solução do sistema

array([[0.73170732],
       [0.17073171]])

# 4. Determinante

Podemos pensar no determinante como um número associado a uma matriz quadrada $A_{m \times n}$. Denotamos $\det A$.

Dada a matriz V = $\begin{bmatrix}
1 & 2 & 3 & 4\\
4& 3 & 2 & 1\\
0 & 2 & 4  & 6 \\
 5 & 7 & 9 & 11 \\
\end{bmatrix}$ encontremos det (V).

Basta utilizar a função np.linalg.det()

In [49]:
V=np.array([[1, 2, 3, 4], [4, 3, 1, 1], [0, 2, 4, 6], [5, 7, 9, 1]])

In [50]:
round (np.linalg.det(V))

-20

# 5. Produto interno

Produto interno canônico:

$\mathbf{x} = \left(x_1, x_2, \dots, x_n \right)$<br>
$\mathbf{y} = \left(y_1, y_2, \dots, y_n \right)$

$\left \langle \mathbf{x}, \mathbf{y} \right \rangle = x_1y_1+x_2y_2+x_3y_3+ \dots x_ny_n$

In [51]:
i = np.array([1, 0, 0])
j = np.array([0, 1, 0])
k = np.array([0, 0, 1])

In [52]:
np.inner(i,j)

0

In [53]:
np.inner(j,k)

0

Se dois vetores $\mathbf{x},\mathbf{y}$, em um dado espaço vetorial possuem produto interno nulo, então esses vetores são ortogonais.

# 6. Norma

Seja $\mathbf{x} \in \mathbb{R}^n$, o número $|\mathbf{x}|$ é denominado norma euclidiana ou distância, tal que:


$$ |\mathbf{x}| = \sqrt{\left \langle \mathbf{x}, \mathbf{x} \right \rangle } = \sqrt{x_1^2+x_2^2+\dots +x_n^2}$$

# 7. Combinação Linear

Sejam $v_1, v_2, \dots v_n$ vetores de um espaço vetorial $V$ e os escalares reais $a_1, a_2, \dots a_n$. Qualquer vetor $v \in V$, tal que $v = a_1v_1+a_2v_2+a_3v_3+\dots a_nv_n$ é uma combinação linear dos vetores $v_1, v_2, \dots, v_n$.

In [54]:
u = np.array([1, 0])
v = np.array([0, 1])
w = np.array([3, 2])

In [55]:
3*u+2*v

array([3, 2])

# <b> 8. Hands On! - Parte 1</b>

1. Encontre WI sendo W = $\begin{bmatrix}
1 & 3 & 0 & 20\\   
2 &-1 & 10 & 13\\
3 & 4 & 10 & 0\\
4 & 9 & -1 & 0 \\
\end{bmatrix}$ e I =  $\begin{bmatrix}
2 & 0 \\
-4 & 11 \\
5 &-2 \\
 6 & 0 \\
\end{bmatrix}$

2. Construa uma matriz $5 \times 5$ e encontre traço, diagonal principal e secundária. 

3. Crie uma matriz $2 \times 2$ somente com elementos pares e calcule seu determinante.

4. Represente os sistemas abaixo  na forma matricial e encontre as respectivas soluções.

a) $\begin{cases}
2x+y=5\\
x-3y=0 \\
\end{cases}$ 

b)$\begin{cases}
2a+b+c=-1\\
a+c=0 \\
-3a+5b-c=2\\
\end{cases}$ 


5.  Determine a inversa das matrizes: 
<br>
a) H =  $\begin{bmatrix}
1 & 0 \\   
3 & 0\\
\end{bmatrix}$
<br>
b) I = $\begin{bmatrix}
1 & 0 & 0\\   
1 & 3 & 1\\
1 & 2 & 0\\
\end{bmatrix}$

# <b>9. Hands On! - Parte 2</b>

1. Com base nos dados gerados a seguir obtenha a matriz de coeficientes da regressão linear e em seguida utilize a biblioteca Statsmodels para verificar os resultados obtidos.

In [56]:
from sklearn.datasets import make_regression
X, y = make_regression(n_samples = 1000, n_features = 10, random_state = 99)

$$\hat{\beta}_{ols} = (X'X)^{-1}(X'y)$$

2. Use a biblioteca sklearn para ajustar um modelo de regressão linear com base nas matrizes anteriores, calcule ainda outras métricas de avaliação da regressão. Use a função train_test_split() para separar os dados em treino e teste com random_state igual a 55. 

3. Faça: 

a. Importe o banco de dados anexo nesta aula (kc_house_data.csv);

b. Mostre as 5 primeiras linhas;

c. Mostre as colunas e o índice do dataset;

d. Mostre o shape do dataset;

e. Mostre informações do objeto criado com a função info();

f. Mostre o dtype de cada coluna;

g. Remova as seguintes colunas: 'id', 'date', 'zipcode', 'lat', 'long';

h. Verifique se há missing data no dataset;

i. Mostre estatísticas descritivas do dataset com a função describe();

j. Calcule a matriz de correlação;

l. Calcule a matriz de covariância;

m. Faça um mapa de calor com base na matriz de correlação, use o módulo Seaborn;

n. Faça um gráfico das relações entre as variáveis do dataset com a função pairplot do módulo Seaborn;

o. Defina a variável target (coluna 'price') e armazene em uma variável;

p. Defina as variáveis preditoras, que serão utilizadas para explicar o preço, e armazene em uma variável;

q. Use a função train_test_split do sklearn para separar o dataset em dados de treino e teste, defina o test_size = 0.3 e random_state = 33;

r. Crie um modelo de regressão linear e ajuste aos dados de treino, use: from sklearn.linear_model import LinearRegression;

s. Calcule o coeficiente de determinação do modelo com a função score(), passando os dados de teste;

# Próximos passos: Rede Neural

* https://www.deeplearningbook.org/

# Adendos

<b>Propriedades da soma de matrizes</b> <br>
Considerando as matrizes A, B e C de mesma ordem $m x n$ temos que: 
1. $\mathbf {A} +\mathbf {B} = \mathbf{B+A} $ (comutatividade)
2. $\mathbf {A}+\mathbf{(B+C)} = \mathbf{(A+B)}+C$ (associatividade)
3. $\mathbf {A}+\mathbf{0} = \mathbf{A}$ 

<b>Propriedades da multiplicação por escalar </b> <br>
Sejam as matrizes A e B de mesma ordem e as constantes reais $k$, $k_1$, $k_2$, temos que:
1. $k(\mathbf{A+B}) = k\mathbf{A}+k\mathbf{B}$
2. $(k_1+k_2)\mathbf{A} = k_1\mathbf{A}+k_2\mathbf{A}$
3. $k\mathbf{A} = \mathbf{0} $, em que k=0

<b>Propriedades da Multiplicação de Matrizes</b>
1. Em geral $\mathbf{AB}\neq\mathbf{BA}$.
2. $\mathbf{AI} = \mathbf{IA} = \mathbf{A} $ (o que justifica o nome da matriz identidade)
3. $\mathbf{A(B+C)} = \mathbf{AB}+\mathbf{AC}$ (distributividade à esquerda da multiplicação)
4. $\mathbf{(A+B)C} = \mathbf{AC+BC} $ (distributividade à direita da multiplicação)
5. $\mathbf{(AB)C = A(BC)} $ (associatividade)
6. $\mathbf{(AB)' = B'A'} $
7. $\mathbf{0 \cdot A = 0}$ e $\mathbf{A \cdot 0 = 0}$

<b>Propriedades da transposição de matrizes</b>
1. Uma matriz é simétrica se, e somente se ela é igual à sua transposta, ou seja, $\mathbf{A=A'}$.
2. $\mathbf{A''=A}$.
3. $\mathbf{(A+B)'=A'+B'}$.
4. $\mathbf{(kA)'=kA'}$, em que k é um escalar.

<b>Propriedades do traço</b>
1. $tr\mathbf{(A+B)} = tr\mathbf{(B+A)}$
2. $tr\mathbf{(\alpha \cdot A)} = \alpha \cdot tr\mathbf{(A)}$, com $\alpha \in \mathbb{R} $
3. $tr\mathbf{(A)} = tr\mathbf{(A')} $
4. $tr\mathbf{(I_{n})} = n$
5. $tr\mathbf{(AB)} = tr\mathbf{(BA)}$